# Generated by Django 2.0.2 on 2018-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_grouprequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='usercount',
            field=models.IntegerField(default=0),
        ),
    ]
