# Generated by Django 2.0.2 on 2018-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sendrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chracter',
            field=models.CharField(default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailalert',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
