# Generated by Django 2.0.2 on 2018-03-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180305_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(default='1', max_length=50, null=True),
        ),
    ]
