# Generated by Django 2.0.2 on 2018-03-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress',
            new_name='address',
        ),
    ]
