# Generated by Django 2.0.2 on 2018-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180308_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
